script = [
"GALADRIEL (V.O.)",
"The world is changed. I feel it in the water.",
"I feel it in the earth. I smell it in the air.",
"Much that once was is lost, for none now live",
"who remember it.",
"It began with the forging of the Rings of",
"Power. Three were given to the Elves, immortal,",
"wisest and fairest of all beings. Seven were",
"given to the Dwarves, great miners and",
"craftsmen of the mountain halls. And nine, nine",
"rings were gifted to the race of Men, who above",
"all else desire power. For within these rings",
"was bound the power and the will to rule each",
"race. But they were all of them deceived, for",
"deep in the land of Mordor, the Dark Lord",
"Sauron forged another ring, a master ring, and",
"into this ring he poured all his cruelty, his",
"malice and his will to dominate every living",
"thing. One ring to rule them all. One by one,",
"the free peoples of Middle Earth fell to the",
"power of the Ring, but there were some who",
"resisted. A last alliance of men and elves",
"marched against the armies of Mordor, and on",
"the very slopes of Mount Doom, they fought for",
"the freedom of Middle-Earth. Victory was near,",
"but the power of the ring could not be undone.",
"SAURON appears, crushing a dozen MEN with each blow of his",
"huge mace.",
"GALADRIEL (V.O.)",
"It was in this moment, when all hope had",
"faded, that Isildur, son of the king, took up",
"his father's sword.",
"ISILDUR picks up sword, SAURON breaks it, but ISILDUR uses",
"the broken blade to cut off SAURON'S fingers, and the RING.",
"GALADRIEL (V.O.)",
"And Sauron, enemy of the free peoples of",
"Middle-Earth, was defeated. The Ring passed to",
"Isildur, who had this one chance to destroy",
"evil forever, but the hearts of men are easily",
"corrupted. And the ring of power has a will of",
"its own. It betrayed Isildur, to his death.",
"ISILDUR attacked by goblins, dies in the river, and the",
"RING is lost in the water.",
"GALADRIEL (V.O.)",
"And some things that should not have been",
"forgotten were lost. History became legend.",
"Legend became myth. For two and a half thousand",
"years, the ring passed out of all knowledge.",
"Until, when chance came, the ring ensnared",
"another bearer.",
"GOLLUM finds the RING in the riverbed.",
"GOLLUM",
"My Precious, my own.",
"GALADRIEL (V.O.)",
"The ring came to the creature Gollum, who took",
"it deep into the tunnels under the Misty",
"Mountains, and there it consumed him.",
"GOLLUM",
"It came to me, my own, my love, my Precious.",
"GALADRIEL (V.O.)",
"The ring gave to Gollum unnatural long life.",
"For five hundred years it poisoned his mind,",
"and in the gloom of Gollum's cave it waited.",
"Darkness crept back into the forests of the",
"world. Rumor grew of a shadow in the East,",
"whispers of a nameless fear, and the Ring of",
"Power perceived that its time had come. It",
"abandoned Gollum, but then something happened",
"that the Ring did not intend. It was picked up",
"by the most unlikely creature imaginable. A",
"hobbit, Bilbo Baggins, of the Shire.",
"BILBO",
"What's this? A Ring!",
"GOLLUM",
"Lost! My Precious is lost!",
"GALADRIEL (V.O.)",
"For the time will soon come when hobbits will",
"shape the fortunes of all.",
"Shire 60 years later",
"FRODO reading a book under a tree, hears GANDALF approach",
"singing. Runs to meet him.",
"FRODO",
"You're late.",
"GANDALF",
"A wizard is never late, Frodo Baggins, nor is",
"he early. He arrives precisely when he means",
"to.",
"They both try to keep a straight face, and fail. FRODO",
"throws himself into GANDALF'S arms for a hug.",
"FRODO",
"It's wonderful to see you again, Gandalf.",
"GANDALF",
"You didn't think I'd miss your Uncle Bilbo's",
"birthday.",
"FRODO",
"What's new in the world? Tell me everything.",
"GANDALF",
"Haven't we grown curious? Most unnatural for a",
"hobbit. What can I tell you? Life in the wide",
"world goes on, much as it has this past age,",
"full of its own comings and goings, scarcely",
"aware of the existence of hobbits. For which I",
"am very grateful.",
"They pass a field where tents and a banner are being set",
"up.",
"GANDALF",
"Ah, the long-expected party. How is the old",
"rascal? I understand this is to be a party of",
"special magnificence.",
"FRODO",
"You know Bilbo. He has the whole place in an",
"uproar.",
"GANDALF",
"Well, that should please him.",
"FRODO",
"Half the Shire's been invited. He's up to",
"something.",
"GANDALF",
"Indeed?",
"FRODO",
"All right, keep your secrets. Before you came",
"along, we Bagginses were very well thought of.",
"Never had any adventures or did anything",
"unexpected.",
"GANDALF",
"If you're referring to that incident with the",
"dragon, I was barely involved. I only gave your",
"uncle a little nudge out the door.",
"FRODO",
"Whatever you did, you have been officially",
"labeled a disturber of the peace.",
"A group of HOBBIT children see GANDALF and come running.",
"CHILDREN",
"Gandalf, Gandalf! Fireworks, Gandalf!",
"GANDALF pretends he won't, but he sets off a butterfly",
"firework for them. An old grandmother's smile at the",
"children's delight turns to a more socially acceptable",
"frown when an annoyed mother becomes witness.",
"FRODO",
"Gandalf, I'm glad you're back.",
"FRODO jumps off the wagon.",
"GANDALF",
"So am I, dear boy, so am I.",
"GANDALF stops his wagon in front of Bag End, passes a sign",
"'No Admittance Except on Party Business', knocks on the",
"door with his staff. A disgruntled voice comes from within.",
"BILBO",
"No thank you! We don't want any more well-",
"wishers, visitors, or distant relations!",
"GANDALF",
"How about very old friends?",
"BILBO",
"Gandalf?",
"GANDALF",
"Bilbo Baggins!",
"BILBO",
"My dear Gandalf!",
"GANDALF",
"One hundred and eleven years old! Who would",
"believe it? You haven't aged a day.",
"BILBO",
"Come in, come in, welcome, would you like some",
"tea? Or perhaps something stronger. I still",
"have some of the Old Winyards left. 1296, a",
"very good year! Almost as old as I am! My",
"Father put it down. What say we open one?",
"BILBO puts GANDALF'S hat and staff away.",
"GANDALF",
"Just tea, thank you.",
"GANDALF knocks the chandelier, steadies it, and hits his",
"head on the beam when he turns around.",
"BILBO",
"I was expecting you last week, but you come",
"and go as you please...",
"BILBO gathers food while GANDALF looks at the maps spread",
"out on BILBO'S table.",
"BILBO",
"I can make you some eggs if you like...",
"BILBO comes into the room, but GANDALF isn't there.",
"GANDALF appears from behind him.",
"GANDALF",
"Just tea.",
"BILBO",
"Yes, right, you don't mind if I do?",
"BILBO has a mouthful of food already.",
"GANDALF",
"Oh, no, not at all.",
"Someone knocks on the door.",
"BILBO",
"I'm not at home! I need to get away from these",
"confounded relatives, hanging on the bell all",
"day, never giving me a moment's rest. I want to",
"see mountains again, Gandalf, mountains! And",
"then find someplace quiet where I can finish my",
"book. Oh, right, the tea.",
"GANDALF",
"You mean to go through with your plan, then?",
"BILBO",
"Yes, everything's in hand. The arrangements",
"have all been made.",
"GANDALF",
"Frodo suspects.",
"BILBO",
"Of course he suspects, he's a Baggins, not",
"some blockheaded Bracegirdle from Hardbottle!",
"GANDALF",
"You will tell him, won't you?",
"BILBO",
"Yes, yes.",
"GANDALF",
"He's very fond of you, you know.",
"BILBO",
"I know. He'd probably come with me if I asked",
"him to, but I think in his heart Frodo is still",
"in love with the Shire. The woods, the fields,",
"little rivers. I'm old, Gandalf. I know I don't",
"look it, but I begin to feel it in my heart. I",
"feel thin, stretched, like butter scraped over",
"too much bread. I need a holiday, a very",
"long holiday, and I don't expect I shall",
"return. In fact, I mean not to!",
"BILBO and GANDALF sit outside Bag-End, smoking.",
"BILBO",
"Old Toby! Finest weed in Southfarthing.",
"BILBO blows a smoke-ring, GANDALF blows a ship, which",
"sails through the ring.",
"BILBO",
"Gandalf, my old friend, this will be a night",
"to remember!",
"GANDALF sets off fireworks - a tree, fountain that turns",
"into jet planes.",
"FRODO sits down next to SAM.",
"FRODO",
"Go on, Sam, ask Rosie for a dance!",
"SAM is too shy.",
"SAM",
"I think I'll just have another ale.",
"FRODO",
"Oh, no you don't!",
"FRODO shoves SAM at ROSIE, they dance off",
"BILBO is telling his story to the young HOBBIT children.",
"BILBO",
"So there I was, at the mercy of three",
"monstrous trolls, and they were arguing about",
"how to cook us! Whether it be turned on a spit,",
"or if they should sit on us one by one and",
"squash us into jelly! They spent so much time",
"arguing the whithertos and whyfors that the",
"first light of the sun crept up over the tops",
"of the trees and turned them all to stone!",
"GANDALF sets off a butterflies firework, which the",
"children try to catch.",
"GANDALF returns to his wagon for more fireworks, and when",
"he leaves, MERRY and PIPPIN come out to steal one of their",
"own. MERRY gives PIPPIN a boost into the wagon, where he",
"roots around and comes up with one.",
"MERRY",
"Not that one! The big one, the big one!",
"PIPPIN grabs the largest firework he can find, which is",
"bright red and huge. They hurry into the tent, so they",
"won't be caught with it. PIPPIN lights it.",
"PIPPIN",
"There!",
"MERRY",
"You're supposed to put it in the ground first!",
"PIPPIN",
"It is in the ground!",
"MERRY",
"Outside!",
"PIPPIN",
"This was your idea!",
"The firework goes off, taking the roof of the tent with",
"it, and leaving MERRY and PIPPIN flat on the ground,",
"covered in soot. The firework goes straight up, becomes a",
"dragon's head, turns around, sprouts wings, and flies in",
"low over the crowd. General panic. FRODO sees it coming and",
"tries to warn BILBO.",
"FRODO",
"Bilbo, watch out for the dragon!",
"BILBO",
"Nonsense, there hasn't been a dragon in these",
"parts for a thousand years!",
"They duck to avoid the dragon, which, having given",
"everyone a good scare, dissolves into a spectacular shower",
"of sparks. MERRY and PIPPIN observe the results and are",
"well pleased.",
"PIPPIN",
"That was good!",
"MERRY",
"Let's get another one!",
"GANDALF comes up behind and grabs MERRY and PIPPIN by",
"their ears.",
"GANDALF",
"Meriadoc Brandybuck, and Peregrin Took. I",
"might have known.",
"MERRY and PIPPIN end up washing dishes in penance. Several",
"HOBBITS go by carrying an enormous cake laden with candles,",
"and BILBO stands up.",
"Speech! Speech!",
"BILBO",
"My dear Bagginses and Boffins, Tooks and",
"Brandybucks, Gubbs, Chubbs, Hornblowers,",
"Bolgers, Bracegirdles and Proudfoots!",
"A HOBBIT",
"Proudfeet!",
"BILBO",
"Today is my one hundred and eleventh birthday!",
"Alas, eleventy one years is much too short a",
"time to live among such excellent and admirable",
"hobbits! I don't know half of you half as well",
"as I should like and I like less than half of",
"you half as well as you deserve! I have things",
"to do. I've put this off for far too long. I",
"regret to announce this is the end! I'm going",
"now. I bid you all a very fond farewell!",
"Goodbye.",
"BILBO puts on the ring and vanishes, to the astonishment",
"of everyone except GANDALF. Footsteps up the path to Bag",
"End. Door opens. BILBO appears, taking off the RING. Puts",
"it in his pocket. Chooses a staff from beside the door.",
"GANDALF has arrived before him.",
"GANDALF",
"I suppose you thought that was terribly",
"clever.",
"BILBO",
"Come on, Gandalf! Did you see their faces?",
"GANDALF",
"There are a good many magic rings in the",
"world, Bilbo, and none of them should be used",
"lightly!",
"BILBO",
"It was just a bit of fun. Oh, I suppose you're",
"right, as usual.",
"BILBO gathers some things to take with him.",
"BILBO",
"You will keep an eye on Frodo, won't you?",
"GANDALF",
"Two eyes, as often as I can spare them.",
"BILBO",
"I'm leaving everything to him.",
"GANDALF",
"And this ring of yours, is that staying, too?",
"BILBO",
"Yes, it's in an envelope, on the mantelpiece.",
"GANDALF looks on the mantel.",
"BILBO",
"Wait, no, it's here in my pocket. Isn't that",
"odd, now? Yet, why not? Why shouldn't I keep",
"it?",
"GANDALF",
"I think you should leave the ring behind. Is",
"that so hard?",
"BILBO",
"Well, no, and yes. Now it comes to it.",
"I don't feel like parting with it! I found it!",
"It came to me!",
"GANDALF",
"There's no need to get angry.",
"BILBO",
"And what if I'm angry! It's your fault! It's",
"mine. My own, my precious...",
"GANDALF",
"Precious? It's been called that before, but",
"not by you.",
"BILBO",
"What business is it of yours what I do with my",
"own things?",
"GANDALF",
"I think you've had that ring quite long",
"enough.",
"BILBO",
"You want it for yourself!",
"A shadow draws around GANDALF, revealing the power he",
"usually keeps hidden.",
"GANDALF",
"Do not take me for some conjuror of cheap",
"tricks! I am not trying to rob you! I'm trying",
"to help you.",
"The shadow retreats, and GANDALF is the kindly old man",
"again. BILBO runs to him.",
"GANDALF",
"All your long years, we have been friends.",
"Trust me now as you once did. Let it go.",
"BILBO",
"You're right. The ring must go to Frodo. It's",
"late, and the road is long. Yes, it is time.",
"BILBO gathers his pack and heads out the door. GANDALF",
"stops him on the doorstep.",
"GANDALF",
"Bilbo, the ring is still in your pocket.",
"BILBO",
"Oh, yes.",
"BILBO takes out the ring, holds it on his palm, and with a",
"great effort, turns his hand until the ring slips off and",
"drops on the floor. BILBO walks out, takes a deep breath.",
"BILBO",
"I've thought of an ending for my book. 'And he",
"lived happily ever after, to the end of his",
"days.'",
"GANDALF",
"And I'm sure you will, old friend.",
"BILBO",
"Good bye, Gandalf.",
"They shake hands, friends as always.",
"GANDALF",
"Goodbye, dear Bilbo.",
"Exit BILBO, singing.",
"GANDALF",
"Until our next meeting.",
"GANDALF reaches down to pick up the RING, sees the EYE,",
"and leaves it where it is. Sits in front of the fire,",
"thinking about BILBO'S words, and the ring'S history.",
"BILBO",
"It's mine, my own, my precious.",
"GANDALF",
"Riddles in the dark... Precious...",
"FRODO",
"Bilbo!",
"FRODO enters, sees the ring and picks it up.",
"FRODO",
"He's gone, hasn't he? He talked about it for",
"so long, I never really believed he would do",
"it. Gandalf?",
"GANDALF looks over, sees FRODO has the RING.",
"GANDALF",
"Bilbo's Ring. He's gone to stay with the",
"elves. He's left you Bag End, along with all",
"his possessions. The Ring is yours now.",
"GANDALF holds out an envelope, FRODO slips the RING",
"inside. GANDALF seals it with wax.",
"GANDALF",
"Put it somewhere out of sight.",
"FRODO",
"Where are you going?",
"GANDALF heads for the door.",
"GANDALF",
"There are things I need to see to.",
"FRODO",
"What things?",
"GANDALF",
"Questions, questions that need answering.",
"FRODO",
"But you've only just arrived! I don't",
"understand.",
"GANDALF",
"Neither do I. Keep it secret. Keep it safe.",
"GANDALF rides to the White city, sees fire over the",
"mountains. BARAD-DUR rebuilt, a voice screams 'Shire!",
"Baggins!' The Nine ride out the gate. GANDALF looks through",
"the library in the White City, finds the manuscript of",
"ISILDUR'S tale.",
"The year 3434 of the Second Age. Here follows",
"the account of Isildur, High King of Gondor,",
"and the finding of the Ring. The Ring of power",
"has come to me. It will become an heirloom of",
"my kingdom. All those who follow in my",
"bloodline will be bound to its fate, for I will",
"risk no hurt to the Ring. It is precious to me,",
"though I buy it with a great pain. The markings",
"on the band fade, the writing that was once as",
"bright as red flame has all but disappeared, a",
"secret now only fire can tell.",
"A HOBBIT cutting wood is startled by a DARK RIDER. His dog",
"sensibly retreats into the house.",
"N",
"Shire. Baggins.",
"HOBBIT",
"No Bagginses here. They're all up in",
"Hobbitton. That way.",
"He follows his dog as the RIDER turns toward HOBBITTON.",
"FRODO returns home from the inn, the window is open and",
"all is dark. GANDALF grabs his shoulder from behind.",
"GANDALF",
"Is it secret? Is it safe?",
"FRODO gets out the envelope, GANDALF throws it in the",
"fire.",
"FRODO",
"What are you doing?",
"Envelope burns away, revealing the RING. GANDALF retrieves",
"it from the fire with tongs.",
"GANDALF",
"Hold out your hand, Frodo. It's quite cool.",
"What can you see? Can you see anything?",
"FRODO",
"Nothing. There's nothing. Wait. There are",
"markings. It's some form of Elvish, but I can't",
"read it.",
"GANDALF",
"There are few who can. The language is that of",
"Mordor, which I shall not utter here.",
"FRODO",
"Mordor?",
"GANDALF",
"In the common tongue, it reads, One ring to",
"rule them all, one ring to find them. One ring",
"to bring them all and in the darkness bind",
"them.",
"GANDALF",
"This is the One Ring, forged by Sauron in the",
"fires of Mount Doom. Isildur took it from the",
"hand of Sauron himself.",
"FRODO",
"Bilbo found it, in Gollum's cave.",
"GANDALF",
"For sixty years, it lay quiet in Bilbo's",
"keeping, prolonging his life, delaying old age.",
"But no longer. There is evil stirring in",
"Mordor. The Ring has awoken. It's heard its",
"master's call.",
"FRODO",
"But he was destroyed. Sauron was destroyed.",
"The RING whispers denial.",
"GANDALF",
"No, Frodo. His spirit endured. Sauron's life-",
"force was bound to the Ring, and the Ring",
"survived. Sauron has returned. His orcs have",
"multiplied. His fortress of Barad-Dur is",
"rebuilt in Mordor. He needs only this Ring to",
"cover all the lands in a second darkness. He is",
"seeking it, seeking it, all his thought is bent",
"on it. The Ring yearns above all else to return",
"to the hand of its master. They are one, the",
"Ring and the Dark Lord. He must never find it.",
"FRODO grabs the RING.",
"FRODO",
"All right, we keep it hidden. We put it away,",
"we never speak of it again. Nobody knows its",
"here, do they?",
"GANDALF is silent.",
"FRODO",
"Do they, Gandalf?",
"GANDALF",
"There was one other who knew that Bilbo had",
"the ring. I looked everywhere for the creature",
"Gollum, but the Enemy found him first.",
"GANDALF",
"I don't know how long they tortured him, but",
"amid the endless screams and inane babble, they",
"heard two words. Shire. Baggins.",
"FRODO",
"Shire. Baggins. But that would lead them here!",
"The RIDERS kill a night watchman. FRODO holds out the RING",
"to GANDALF.",
"FRODO",
"Take it, Gandalf, you must take it!",
"GANDALF",
"You cannot offer me this Ring!",
"FRODO",
"I am giving it to you!",
"GANDALF",
"Don't tempt me! I dare not take this",
"Ring, not even to keep it safe! Understand, I",
"would use this Ring out of a desire to do good,",
"but through me, it would wield a power too",
"great and terrible to imagine.",
"FRODO",
"But it cannot stay in the Shire!",
"GANDALF",
"No. No, it can't.",
"FRODO accepts his duty.",
"FRODO",
"What must I do?",
"GANDALF",
"You must go, and go quickly.",
"FRODO",
"Where?",
"GANDALF",
"Get out of the Shire. Make for the village of",
"Bree.",
"FRODO",
"What about you?",
"GANDALF",
"I will wait for you at the Inn of the Prancing",
"Pony.",
"FRODO",
"And the Ring will be safe there?",
"GANDALF",
"I don't know, Frodo. I don't have any answers.",
"I must see the head of my order. He is both",
"powerful and wise. Trust me, he will know what",
"to do. You must leave the name of Baggins",
"behind you, for that name is not safe outside",
"the Shire. Travel only by day, and stay off the",
"road.",
"FRODO",
"I can cut across country easily enough.",
"GANDALF stops, looking at FRODO, who is within minutes",
"packed, cloaked, and ready for a long and dangerous",
"journey.",
"GANDALF",
"Dear Frodo. Hobbits are the most amazing",
"creatures. You can learn everything there is to",
"know about their ways in a month, and after a",
"hundred years they can still surprise you!",
"Noise outside the window.",
"GANDALF",
"Get down!",
"FRODO drops to the floor, GANDALF reaches out the window",
"with his staff, hits something. Hauls SAM in by the scruff",
"of his neck.",
"GANDALF",
"Confound it all, Samwise Gamgee, have you been",
"eavesdropping?",
"SAM",
"I ain't been dropping no eaves, sir, honest, I",
"was just cutting the grass outside the window,",
"if you follow me.",
"GANDALF",
"A bit late for trimming the verge.",
"SAM",
"I heard raised voices.",
"GANDALF",
"What did you hear? Speak!",
"SAM",
"Nothing important. That is, I heard a good",
"deal about a ring, and a dark lord, and",
"something about the end of the world. Please",
"don't hurt me, sir, don't turn me into anything",
"unnatural.",
"GANDALF",
"No? Perhaps not. I've thought of a better use",
"for you.",
"GANDALF and FRODO walking, GANDALF leading his horse.",
"GANDALF",
"Come along, Samwise, keep up!",
"SAM runs to catch up. The three stop under the trees.",
"GANDALF",
"Be careful, both of you. The enemy has many",
"spies in his service. Birds, beasts. Is it",
"safe?",
"FRODO pats his pocket, where the RING is hidden.",
"GANDALF",
"Never put it on! The servants of the Dark Lord",
"will be drawn to its power. Remember, the Ring",
"is trying to get back to its master. It",
"wants to be found.",
"GANDALF leaves. FRODO and SAM cross fields, going towards",
"BREE. SAM stops on the edge of a field of wheat.",
"SAM",
"This is it.",
"FRODO",
"This is what?",
"SAM",
"If I take one more step, it will be the",
"farthest from home I've ever been.",
"FRODO",
"Come on, Sam. Remember what Bilbo used to say.",
"It's a dangerous thing, Frodo, going out your",
"door. You step onto the road, and if you don't",
"keep your feet, there's no knowing where you'll",
"be swept off to.",
"GANDALF riding to Isengard.",
"SARUMAN",
"Smoke rises from the mountain of Doom. The",
"hour grows late, and Gandalf the Grey rides to",
"Isengard seeking my council. For that is why",
"you have come, is it not, my old friend?",
"GANDALF",
"Saruman.",
"GANDALF and SARUMAN walking outside Isengard.",
"SARUMAN",
"You are sure of this?",
"GANDALF",
"Beyond any doubt.",
"SARUMAN",
"So the One Ring has been found.",
"GANDALF",
"All these long years it was in the Shire,",
"right under my nose.",
"SARUMAN",
"And you had not the wit to see it. Your love",
"of the Halflings' leaf has clearly slowed your",
"mind.",
"GANDALF",
"We still have time, time to counter Sauron, if",
"we act quickly.",
"SARUMAN",
"Time? What time do you think we have?",
"SARUMAN and GANDALF inside Isengard.",
"SARUMAN",
"Sauron has regained much of his former",
"strength. He cannot yet take physical form, but",
"his spirit has lost none of its potency.",
"Concealed in his fortress he sees all. His gaze",
"pierces cloud, shadow, earth and flesh. You",
"know of what I speak. A great eye, lidless,",
"wreathed in flame.",
"GANDALF",
"The Eye of Sauron.",
"SARUMAN",
"He is gathering all evil to him. Very soon he",
"will have assembled an army large enough to",
"assault Middle-earth.",
"GANDALF",
"You know this? How?",
"SARUMAN",
"I have seen it.",
"They enter another room, where a stone sphere lies",
"covered.",
"GANDALF",
"A Palantir is a dangerous tool.",
"SARUMAN uncovers the stone.",
"SARUMAN",
"Why? Why should we fear to use it?",
"GANDALF",
"They are not all accounted for, the lost",
"seeing stones. You do not know who else may be",
"watching.",
"As he re-covers the stone, GANDALF sees the EYE",
"SARUMAN",
"The hour is later than you think. Sauron's",
"forces are already moving. The Nine have left",
"Minas Mordor.",
"GANDALF",
"The Nine?",
"SARUMAN",
"They crossed the river Isen on midsummer's",
"eve, disguised as riders in black.",
"GANDALF",
"They have reached the Shire!",
"SARUMAN",
"They will find the Ring, and kill the one who",
"carries it.",
"GANDALF",
"Frodo!",
"GANDALF tries to leave, but the doors slam, one by one.",
"SARUMAN",
"You did not truly think that a hobbit could",
"contend with the will of Sauron? There are none",
"who can. Against the power of Mordor there can",
"be no victory. We must join him, Gandalf. Join",
"with Sauron. It would be wise, old friend.",
"GANDALF",
"Tell me, friend, when did Saruman the",
"Wise abandon reason for madness?",
"They fight, GANDALF loses his staff and is captured.",
"SARUMAN",
"I offered you the choice of aiding me",
"willingly, but you have elected the way of",
"pain!",
"GANDALF rises toward the roof of Isengard. Darkness.",
"SAM emerges from a corn patch, alone.",
"SAM",
"Mister Frodo? Frodo!",
"FRODO reappears from the path ahead.",
"SAM",
"I thought I'd lost you.",
"FRODO",
"What are you talking about, Sam?",
"SAM",
"It's just something Gandalf said.",
"FRODO",
"What did he say?",
"SAM",
"Don't you lose him, Samwise Gamgee. And I",
"don't mean to.",
"FRODO",
"We're still in the Shire, Sam, what could",
"possibly happen?",
"They get knocked over by MERRY and PIPPIN.",
"PIPPIN",
"Frodo! Look, Merry, it's Frodo!",
"SAM",
"You get off him!",
"SAM shakes off MERRY, picks PIPPIN off FRODO by the scruff",
"of his neck.",
"MERRY hands SAM an armful of vegetables.",
"MERRY",
"Hold these.",
"PIPPIN",
"What's the meaning of this?",
"SAM",
"You've been into Farmer Maggott's crop!",
"They start running through a cornfield.",
"MERRY",
"I don't know what he's so upset about, it's",
"only a few carrots.",
"PIPPIN",
"And some cabbages. And the three bags of",
"potatoes we lifted last week. And the mushrooms",
"the week before that.",
"MERRY",
"Yes, Pippin! My point is, he's obviously",
"overreacting!",
"They all fall over a cliff, land in a heap.",
"PIPPIN lands inches away from a pile of manure.",
"PIPPIN",
"Ooh! That was a close one.",
"MERRY",
"I think I've broken something.",
"MERRY pulls out a broken carrot.",
"SAM",
"Trust a Brandybuck and a Took!",
"MERRY",
"Nonsense! That was just a detour! A shortcut!",
"SAM",
"Shortcut to what?",
"PIPPIN",
"Mushrooms!",
"Three start gathering mushrooms into a bag.",
"FRODO looks down the road.",
"FRODO",
"I think we should get off the road.",
"Something dark approaches.",
"FRODO",
"Get off the road, quick!",
"They hide under the roots of a tree. The RINGWRAITH comes,",
"on his horse. Gets off the horse, sniffing as though he can",
"smell that the RING is close. A spider crawls out, and a",
"centipede, and a lot of worms. For the first time, the RING",
"tries to impose its will on FRODO, pushing him to put it on",
"so they will be found. SAM distracts him. MERRY throws",
"something to distract the WRAITH, and they run away.",
"PIPPIN",
"What was that?",
"It is dark, they have been running for some time, watching",
"for the RIDER.",
"Anything?",
"FRODO",
"Nothing.",
"MERRY",
"That dark rider was looking for something, or",
"someone. Frodo?",
"RIDER appears, in the distance.",
"Get down!",
"They hide again.",
"FRODO",
"I have to leave the Shire. Sam and I have to",
"get to Bree.",
"MERRY",
"Bucklebury ferry. Follow me.",
"They run, but the horse is right behind them. FRODO gets",
"separated from the rest, who get to the ferry ahead of him.",
"MERRY",
"Sam, get the ropes!",
"They untie the raft.",
"Run, Frodo!",
"The RIDER is right behind FRODO.",
"FRODO",
"Go!",
"FRODO jumps off the dock, and just makes it onto the",
"ferry. The RIDER stops at the water's edge.",
"FRODO",
"Where is the nearest crossing?",
"MERRY",
"Brandywine bridge. Twenty miles.",
"They look back to see three RIDERS now, heading for the",
"bridge.",
"Four HOBBITS arrive at BREE, in the pouring rain, knock on",
"the gate. Guard answers. Seeing no one at the window, he",
"opens the lower window.",
"GUARD",
"What do you want?",
"FRODO",
"We are headed for the Prancing Pony.",
"GUARD",
"Hobbits. Four hobbits! What business brings",
"you to Bree?",
"FRODO",
"We wish to stay at the inn. Our business is",
"our own.",
"GUARD",
"Very well, young sir, didn't mean no offence",
"by it. It's my job to ask questions after",
"nightfall. There's been talk of some strange",
"folk about. Can't be too careful.",
"Arrival at the Prancing Pony.",
"FRODO",
"Excuse me?",
"BARLIMAN",
"Good evening, little Masters. If you're",
"looking for accommodation, we have some cozy",
"hobbit-sized rooms available, Mr...?",
"FRODO",
"Underhill. My name's Underhill. We're friends",
"of Gandalf the Grey. Would you tell him we've",
"arrived?",
"BARLIMAN",
"Gandalf? Elderly chap, big grey beard, pointy",
"hat. Haven't seen him in six months.",
"SAM",
"What do we do now?",
"FRODO",
"He'll come, Sam. He'll be here.",
"MERRY sits down.",
"PIPPIN",
"What's that?",
"MERRY",
"This, my friend, is a pint.",
"PIPPIN",
"It comes in pints? I'm going to get one.",
"SAM",
"Pippin, you've had a whole half already.",
"PIPPIN goes to the bar for his pint.",
"SAM",
"That man's done nothing but stare at you since",
"we came in.",
"FRODO stops the innkeeper.",
"FRODO",
"That man in the corner, who is he?",
"BARLIMAN",
"He's one of them Rangers. Dangerous folk, they",
"are, wandering the wilds. What his right name",
"is I've never heard, but round here he's known",
"as Strider.",
"FRODO",
"Strider.",
"RING tries again to get FRODO to put it on, whispering",
"Baggins, Baggins.",
"PIPPIN",
"Baggins? Sure I know a Baggins - Frodo",
"Baggins, over there. He's my second cousin,",
"once removed on his Mother's side.",
"FRODO runs toward PIPPIN, at the bar.",
"FRODO",
"Pippin!",
"PIPPIN",
"Steady on!",
"FRODO trips, the ring falls on his finger. The Nine turn",
"towards BREE. FRODO sees the EYE for the first time. FRODO",
"takes off the ring and is dragged off by STRIDER.",
"STRIDER",
"You draw far too much attention to yourself,",
"Mr. Underhill.",
"FRODO",
"What do you want?",
"STRIDER",
"A little more caution from you, that is no",
"trinket you carry.",
"FRODO",
"I carry nothing.",
"STRIDER",
"Indeed? I can avoid being seen if I wish, but",
"to disappear entirely - that is a rare gift.",
"FRODO",
"Who are you?",
"STRIDER",
"Are you frightened?",
"FRODO",
"Yes.",
"STRIDER",
"Not nearly frightened enough. I know what",
"hunts you.",
"The three HOBBITS come in, threatening STRIDER if he has",
"hurt FRODO.",
"STRIDER",
"You have a stout heart, little hobbit, but it",
"will not save you. You can no longer wait for",
"the wizard, Frodo. They are coming.",
"Four of the Nine arrive at BREE, break down the gate and",
"squash the doorkeeper. They find the room where HOBBITS",
"appear to be sleeping and stab them, become angry when they",
"find they have been tricked. FRODO is awake already,",
"watching STRIDER watching out the window. The others wake",
"at the noise.",
"FRODO",
"What are they?",
"STRIDER",
"They were once men. Great kings of men, but",
"Sauron the Deceiver gave them nine rings of",
"power, and, blinded by their greed, they took",
"them without question, one by one falling into",
"darkness. Now they are slaves to his will. They",
"are the Nazgul, Ringwraiths, neither living nor",
"dead. At all times they feel the presence of",
"the ring, drawn to the power of the One. They",
"will never stop hunting you.",
"The party leaves BREE, avoiding the roads.",
"FRODO",
"Where are you taking us?",
"STRIDER",
"Into the wilds.",
"They walk for a while.",
"MERRY",
"How do we know this Strider is a friend of",
"Gandalf's?",
"FRODO",
"We have no choice but to trust him.",
"SAM",
"Where is he taking us?",
"STRIDER",
"To Rivendell, Master Gamgee, the home of",
"Elrond.",
"SAM",
"Did you hear that? Rivendell! We're going to",
"see the elves!",
"HOBBITS stop.",
"STRIDER",
"Gentlemen, we do not stop till nightfall.",
"PIPPIN",
"What about breakfast?",
"STRIDER",
"You have had it.",
"PIPPIN",
"We've had one, yes, what about second",
"breakfast?",
"MERRY",
"I don't think he knows about second breakfast,",
"Pip.",
"PIPPIN",
"What about elevenses? Luncheon? Afternoon tea?",
"Dinner? Supper? Do you think he knows about",
"them?",
"MERRY",
"I wouldn't count on it.",
"STRIDER throws an apple to MERRY, who catches it, and",
"PIPPIN, who gets hit in the head.",
"SARUMAN using Palantir.",
"SARUMAN",
"The power of Isengard is at your command,",
"Sauron, Lord of the Earth.",
"Build me an army worthy of Mordor.",
"SARUMAN sits in his study, looking uncomfortable. ORCS",
"enter, looking out of place.",
"ORC",
"What orders from Mordor, my lord? What does",
"the High command?",
"SARUMAN",
"We have work to do.",
"ORCS begin pulling down trees. GANDALF observes from his",
"prison atop the tower.",
"ORC",
"The trees are strong, my lord. Their roots go",
"deep.",
"SARUMAN",
"Rip them all down.",
"FRODO and company cross harsh lands.",
"STRIDER",
"This was once the great watchtower of Amon",
"Sul. We will rest here tonight.",
"STRIDER unwraps four swords, passes them out to HOBBITS.",
"STRIDER",
"These are for you. Keep them close. I'm going",
"to have a look around. Stay here.",
"FRODO is napping, wakes up to find the others have built a",
"fire.",
"FRODO",
"What are you doing?",
"MERRY",
"Sausages, tomatoes, nice crispy bacon!",
"SAM",
"We saved some for you!",
"FRODO",
"Put it out, you fools, put it out!",
"FRODO stamps out the fire.",
"PIPPIN",
"That's nice, ash on my tomatoes.",
"They look over the edge to find RINGWRAITHS approaching.",
"FRODO pulls out his sword.",
"FRODO",
"Go!",
"HOBBITS retreat to the center of the ruin, stand back to",
"back, not knowing where the WRAITHS will come from. Five",
"WRAITHS enter the ruin.",
"SAM",
"Back, you devils!",
"SAM tries to fight them, gets tossed aside. MERRY and",
"PIPPIN step in front, get pushed away. FRODO drops his",
"sword, backs away. Falls down. The WRAITHS seem to know he",
"has the RING. He pulls it out of his pocket, and they all",
"focus on it. WRAITHS close in, and he puts on the ring. The",
"RINGWRAITH leader tries to take the ring. It takes all",
"FRODO'S strength to pull it away. The Wraith seems angry",
"that FRODO has denied him and stabs him in the shoulder.",
"STRIDER attacks WRAITHS, FRODO takes the ring off.",
"SAM",
"Frodo!",
"SAM runs to FRODO, now that he can see him.",
"FRODO",
"Oh, Sam!",
"STRIDER stabs and sets fire to WRAITHS, they go away.",
"SAM",
"Strider! Help him!",
"STRIDER picks up the sword, but the blade dissolves into",
"dust.",
"STRIDER",
"He's been stabbed with a Morgul blade. This is",
"beyond my skill to heal, he needs elvish",
"medicine.",
"STRIDER picks up FRODO, who is in a lot of pain.",
"STRIDER",
"Hang on, Frodo.",
"SAM",
"It's six days to Rivendell! He'll never make",
"it!",
"FRODO",
"Gandalf. Gandalf!",
"GANDALF is still imprisoned on top of Isengard, which is",
"now barren, with deep holes in the ground where ORCS mine",
"and forge weapons and armor. A moth flutters by, and",
"GANDALF catches it, speaks to it, and lets it go. SARUMAN",
"oversees his latest project - a new type of creature is",
"being bred in pits of mud. One awakens, and immediately",
"kills the ORC tending it. SARUMAN seems pleased.",
"STRIDER carries FRODO, they stop at the three stone",
"TROLLs.",
"SAM",
"Mr. Frodo? He's going cold!",
"PIPPIN",
"Is he going to die?",
"STRIDER",
"He is passing into the shadow world. Soon he",
"will become a wraith like them.",
"There is a cry, not far enough away.",
"MERRY",
"They're close!",
"STRIDER",
"Sam, do you know the Athelas plant?",
"SAM",
"Athelas?",
"STRIDER",
"Kingsfoil.",
"SAM",
"Kingsfoil? Aye, it's a weed.",
"STRIDER",
"It may help to slow the poison.",
"SAM and STRIDER search for plant, STRIDER finds it.",
"ARWEN",
"What's this? A Ranger caught off his guard?",
"FRODO sees ARWEN as she is from the shadow world- a",
"beautiful, glowing elf-maiden in white robes.",
"ARWEN",
"Frodo, I am Arwen. I've come to help you. Hear",
"my voice. Return to the light.",
"A black stain is spreading across FRODO'S eyes as the",
"poison takes over.",
"Who is she?",
"SAM",
"She's an elf!",
"ARWEN",
"He's fading. He's not going to last. We have",
"to get him to my father.",
"STRIDER chews up some of the Kingsfoil and presses it into",
"the wound.",
"ARWEN",
"I've been looking for you for two days. There",
"are five wraiths behind you. Where the other",
"four are I do not know.",
"STRIDER lifts FRODO onto ARWEN'S horse.",
"STRIDER",
"Stay with the hobbits. I will send horses for",
"you.",
"ARWEN",
"I am the faster rider. I will take him.",
"STRIDER",
"The road is too dangerous.",
"ARWEN",
"If I can get across the river, the power of my",
"people will protect him. I do not fear them.",
"ARWEN gets on her horse, behind FRODO.",
"STRIDER",
"Arwen. Ride hard and don't look back.",
"SAM",
"What are you doing? Those wraiths are still",
"out there!",
"ARWEN and FRODO ride, chased by some RINGWRAITHS. WRAITHS",
"try to influence FRODO, either to give in to the poison or",
"to put the RING on.",
"ARWEN",
"No! Frodo, you must not!",
"They get to the river, ARWEN stops partway across. RIDERS",
"or their horses do not want to enter the river.",
"N",
"Give up the halfling, she-elf!",
"ARWEN draws her sword.",
"ARWEN",
"If you want him, come and claim him!",
"RIDERS start to cross the river. ARWEN speaks to the river",
"in elvish, and it rises suddenly. A flood of water washes",
"down the riverbed, led by white horse-shapes. WRAITHS are",
"washed away. FRODO is losing his battle. ARWEN gets off her",
"horse, lays him on the ground.",
"ARWEN",
"No, Frodo! Don't give in! Not now!",
"ARWEN",
"Let what grace is given me be passed to him.",
"Let him be spared. Save him.",
"FRODO'S world dissolves into light.",
"FRODO wakes up, in bed.",
"FRODO",
"Where am I?",
"GANDALF",
"You are in the House of Elrond, and it is ten",
"in the morning, on October the 24th, if you",
"want to know.",
"FRODO",
"Gandalf?",
"GANDALF",
"Yes, I'm here. And you're lucky to be here,",
"too. A few more hours and you would have been",
"beyond our aid, but you have some strength in",
"you, dear hobbit.",
"FRODO",
"What happened? Why didn't you meet us?",
"GANDALF",
"I am sorry. I was delayed.",
"Top of the tower.",
"SARUMAN",
"The friendship of Saruman is not lightly cast",
"aside. One ill turn deserves another.",
"SARUMAN holding GANDALF out over the edge of the tower.",
"SARUMAN",
"It is over. Embrace the power of the Ring or",
"embrace your own destruction.",
"GANDALF",
"The ring has but one master. Only one may bend",
"it to his will, and he does not share power.",
"GANDALF jumps off the edge of the tower, King of Eagles",
"catches him and they fly away.",
"SARUMAN",
"So you have chosen death.",
"FRODO",
"Gandalf, what is it?",
"GANDALF",
"Nothing.",
"SAM comes in, and ELROND.",
"SAM",
"Bless you, Frodo, you're awake!",
"GANDALF",
"Sam has hardly left your side.",
"SAM",
"We were that worried about you, weren't we,",
"Mr. Gandalf?",
"GANDALF",
"Thanks to the skills of Master Elrond, you",
"have begun to mend.",
"ELROND",
"Welcome to Rivendell, Frodo Baggins.",
"FRODO meets MERRY and PIPPIN again, and BILBO, looking",
"older.",
"FRODO",
"Bilbo!",
"BILBO",
"Hello, Frodo, my lad!",
"FRODO looking at BILBO'S book.",
"FRODO",
"There and back again, a hobbit's tale, by",
"Bilbo Baggins. This is wonderful!",
"BILBO",
"I meant to go back, wander the paths of the",
"Mirkwood, visit Laketown, see the Lonely",
"Mountain again, but age, it seems, has finally",
"caught up with me.",
"FRODO",
"I miss the Shire. I spent all my childhood",
"pretending I was somewhere else, off with you",
"on one of your adventures, but my own adventure",
"turned out to be quite different. I'm not like",
"you, Bilbo.",
"BILBO",
"My dear boy.",
"SAM packing.",
"SAM",
"Now what have I forgotten?",
"FRODO",
"Packed already?",
"SAM",
"Doesn't hurt to be prepared.",
"FRODO",
"I thought you wanted to see the elves, Sam.",
"SAM",
"I do.",
"FRODO",
"More than anything.",
"SAM",
"I did, but... we did what we set off to do,",
"didn't we? We got the ring this far, to",
"Rivendell, and seeing as how you're on the",
"mend, I thought we'd be off soon. Off home.",
"FRODO",
"You're right, Sam. We did what Gandalf wanted.",
"The Ring will be safe in Rivendell. I am ready",
"to go home.",
"GANDALF and ELROND, watching FRODO and SAM.",
"ELROND",
"His strength returns.",
"GANDALF",
"That wound will never fully heal. He will",
"carry it for the rest of his life.",
"ELROND",
"Yet to have come so far still bearing the",
"ring, the hobbit has shown remarkable",
"resilience to its evil.",
"GANDALF",
"It is a burden he should never have had to",
"bear. We can ask no more of Frodo.",
"ELROND",
"Gandalf, the Enemy is moving. Sauron's forces",
"are massing in the East. The Eye is fixed on",
"Rivendell. Now you tell me Saruman has betrayed",
"us. The list of our allies grows thin.",
"GANDALF",
"His treachery goes deeper than you know. At",
"Falcraft, Saruman has crossed orcs with goblin",
"men. He is breeding an army in the caverns of",
"Isengard. An army that can move in sunlight,",
"and travel great distances at speed. Saruman is",
"coming for the ring.",
"ELROND",
"This evil cannot be concealed by the power of",
"the elves. We do not have the strength to stand",
"against Mordor and Isengard both. The ring",
"cannot stay here.",
"BOROMIR arrives, and LEGOLAS, and a group of DWARVES.",
"ELROND",
"This peril belongs to all Middle-Earth, and",
"they must decide now how to end it. The age of",
"elves is over. My people are leaving these",
"shores. Who will you turn to once we are gone?",
"The dwarves hide in their mountains seeking",
"riches and care not for the troubles of others.",
"GANDALF",
"We must place our hope in men.",
"ELROND",
"Men! The race of men is weak, failing. The",
"blood of Numenor is all but spent, its pride",
"and dignity forgotten. It is because of men",
"that the Ring survives. I was there, three",
"thousand years ago, when Isildur took the ring.",
"I was there when the strength of men failed.",
"ISILDUR takes the RING.",
"ELROND",
"Follow me!",
"ELROND",
"I led Isildur into the heart of Mount Doom,",
"where it was forged, the one place it could be",
"destroyed.",
"ELROND",
"Throw it in the fire! Destroy it!",
"ISILDUR",
"No.",
"ELROND",
"Isildur!",
"ELROND",
"It should have ended that day, but evil was",
"allowed to endure. Isildur kept the Ring. The",
"line of Kings is broken. There is no strength",
"left in the world of men. They are scattered,",
"divided, leaderless.",
"GANDALF",
"There is one who could unite them. Who could",
"reclaim the throne of Gondor.",
"ELROND",
"He turned from that path long ago. He has",
"chosen exile.",
"STRIDER reading a book.",
"BOROMIR",
"The shards of Narsil. The blade that cut the",
"ring from Sauron's hand.",
"He cuts his finger on it.",
"BOROMIR",
"Still sharp. But no more than a broken hilt.",
"The sword falls when BOROMIR tries to replace it on the",
"statue. ARAGORN picks it up, and returns it to its place.",
"ARWEN",
"Why do you fear the past? You are Isildur's",
"heir, not Isildur himself. You are not bound to",
"his fate.",
"STRIDER",
"The same blood flows in my veins, the same",
"weakness.",
"ARWEN",
"Your time will come. You will face the same",
"evil, and you will defeat it. The shadow does",
"not yet hold sway. Not over you, not over me.",
"Do you remember the first time we met?",
"STRIDER",
"I thought I had strayed into a dream.",
"ARWEN",
"Long years have passed since then. You did not",
"have the cares you carry now. Do you remember",
"what I told you?",
"STRIDER",
"You said you would bind yourself to me, and",
"forsake the immortal life of your people.",
"ARWEN",
"And to that I hold. I would rather share one",
"lifetime with you than face all the ages of the",
"world alone. I choose a mortal life.",
"ARWEN gives ARAGORN the flower necklace she wears.",
"STRIDER",
"You cannot give me this.",
"ARWEN",
"It is mine to give to whom I will. Like my",
"heart.",
"A council is gathered of MEN and ELVES and DWARVES and",
"FRODO.",
"ELROND",
"Strangers from distant lands, friends of old.",
"You are summoned here to answer the threat of",
"Mordor. Middle-Earth stands on the brink of",
"destruction. You will unite or you will fall.",
"Each race is bound to this fate, this one doom.",
"ELROND",
"Bring forth the ring, Frodo.",
"FRODO puts the RING on the stand in the center of the",
"council, and seems much relieved to be rid of it.",
"So it is true.",
"The Ring of power.",
"The doom of man.",
"BOROMIR",
"It is a gift, a gift to the foes of Mordor.",
"Why not use this Ring? Long has my father, the",
"Steward of Gondor, kept the forces of Mordor at",
"bay. By the blood of my people are your lands",
"kept safe. Give Gondor the weapon of the enemy.",
"Let us use it against him.",
"STRIDER",
"You cannot wield it. None of us can. The ring",
"answers to Sauron alone. It has no other",
"master.",
"BOROMIR",
"What would a ranger know of this matter?",
"LEGOLAS",
"He is no mere ranger. This is Aragorn, son of",
"Arathorn. You owe him your allegiance.",
"BOROMIR",
"This is Isildur's heir?",
"LEGOLAS",
"And heir to the throne of Gondor.",
"STRIDER",
"Sit down, Legolas.",
"BOROMIR",
"Gondor has no king, Gondor needs no king.",
"GANDALF",
"Aragorn is right. We cannot control it.",
"ELROND",
"We have but one choice. The ring must be",
"destroyed.",
"The RING murmurs its displeasure.",
"GIMLI",
"What are we waiting for?",
"GIMLI picks up his axe and hits the RING. FRODO sees the",
"eye, and the axe is shattered. GIMLI is knocked to the",
"ground.",
"ELROND",
"The ring cannot be destroyed, Gimli, son of",
"Gloin, by any craft that we here possess. It",
"was made in the fires of Mount Doom. Only there",
"can it be unmade. It must be taken deep into",
"Mordor, and cast back into the fiery chasm from",
"which it came. One of you must do this.",
"Silence.",
"BOROMIR",
"One does not simply walk into Mordor. Its",
"black gates are guarded by more than orcs.",
"There is evil there that does not sleep, and",
"the great eye is ever watchful. It is a barren",
"wasteland, riddled with fire, ash and dust. The",
"very air you breathe is a poisonous fume. It is",
"folly. Not with ten thousand men could you do",
"this.",
"LEGOLAS",
"Have you heard nothing that Lord Elrond has",
"said? The Ring must be destroyed!",
"GIMLI",
"And I suppose you think you're the one to do",
"it?",
"BOROMIR",
"And what if we fail? What happens when Sauron",
"takes back what is his?",
"GIMLI",
"I will be dead before I see the Ring in the",
"hands of an elf! Never trust an elf!",
"The RING chants, telling its name, and its terrible",
"purpose, in the language of its master. The council",
"dissolves into arguing, flames spread across the ring as it",
"feeds their distrust and anger.",
"FRODO",
"I will take it.",
"Arguing continues.",
"FRODO",
"I will take it!",
"GANDALF hears, and it pains him that FRODO must continue",
"to carry the RING, but the rest of the council has just",
"demonstrated how easily the RING can influence most people.",
"Silence returns.",
"FRODO",
"I will take the ring to Mordor. Though I do",
"not know the way.",
"GANDALF",
"I will help you bear this burden for as long",
"as it is yours to bear.",
"STRIDER",
"If by my life or my death I can protect you, I",
"will.",
"ARAGORN kneels in front of FRODO.",
"STRIDER",
"You have my sword.",
"LEGOLAS",
"And my bow.",
"GIMLI",
"And my axe.",
"BOROMIR",
"You carry the fate of us all, little one. But",
"if this is truly the will of the council,",
"Gondor will see it done.",
"SAM runs in.",
"SAM",
"Here! Mr. Frodo's not going anywhere without",
"me.",
"SAM takes his place beside FRODO.",
"ELROND",
"Indeed, it is hardly possible to separate the",
"two of you, even when he is summoned to a",
"secret council and you are not. Very well.",
"MERRY and PIPPIN barge in.",
"MERRY",
"We're going, too! You'd have to send us home",
"tied up in a sack to keep us away.",
"PIPPIN",
"Anyway, you need people of intelligence on",
"this sort of mission. Quest. Thing.",
"MERRY",
"Well, that rules you out, Pip.",
"ELROND",
"Nine companions. So be it. You shall be the",
"Fellowship of the Ring.",
"PIPPIN",
"Great. Now, where are we going?",
"BILBO gives FRODO his old sword and armor.",
"BILBO",
"My old sword, Sting. Take it, take it!",
"FRODO",
"It's so light!",
"BILBO",
"Yes. Made by the elves, you know. The blade",
"glows blue when orcs are close. And it's times",
"like those, dear boy, you have to be extra",
"careful. Here's a pretty thing.",
"BILBO holds up a chainmail vest, sized for a HOBBIT.",
"BILBO",
"As light as a feather, and as hard as dragon",
"scales. Let me see you put it on.",
"FRODO starts to take off his shirt.",
"BILBO",
"Oh, my old ring. I should very much like to",
"hold it again, one last time.",
"FRODO knows better, and buttons up his shirt again. BILBO",
"has an evil moment, then recovers.",
"BILBO",
"I'm sorry I brought this upon you, my boy. I'm",
"sorry you must carry this burden. I'm sorry for",
"everything!",
"FRODO comforts him.",
"The company leaves Rivendell, wanders past ruins, over",
"mountains, through fields.",
"GANDALF",
"We must hold to this course west of the Misty",
"Mountains for forty days. If our luck holds,",
"the Gap of Rohan will still be open to us, and",
"from there our road turns east toward Mordor.",
"They stop for lunch, MERRY and PIPPIN practice",
"swordfighting with BOROMIR.",
"BOROMIR",
"Very good. Again!",
"GIMLI",
"If anyone were to ask my opinion, which I note",
"they have not, I would say we're taking the",
"long way around! Gandalf, we could go through",
"the Mines of Moria. My cousin Balin would give",
"us a royal welcome!",
"GANDALF",
"No, Gimli, I would not take the road through",
"Moria unless I had no other choice.",
"ARAGORN adds comments.",
"STRIDER",
"Move your feet!",
"BOROMIR accidentally hurts PIPPIN.",
"PIPPIN",
"Ow!",
"BOROMIR",
"Sorry!",
"PIPPIN drops his sword, kicks BOROMIR in the shins and",
"tackles him. MERRY joins in, and the two of them wrestle",
"BOROMIR to the ground. LEGOLAS notices something on the",
"horizon.",
"SAM",
"What's that?",
"GIMLI",
"It's nothing, just a wisp of cloud.",
"Everyone looks.",
"BOROMIR",
"It's moving fast, against the wind.",
"LEGOLAS",
"Crebain from Dunland! Hide!",
"Everyone gathers possessions, they put out the fire and",
"take cover. When crows leave, they come out again.",
"GANDALF",
"Spies for Saruman. The passage south is being",
"watched. We will have to go over the pass of",
"Caradhras.",
"Climbing a snowy mountain, FRODO falls and rolls down.",
"STRIDER catches him, but the ring is missing. BOROMIR picks",
"it up.",
"STRIDER",
"Boromir.",
"BOROMIR",
"It is a strange fate that we should suffer so",
"much fear and doubt over so small a thing. Such",
"a little thing.",
"STRIDER",
"Boromir! Give the ring to Frodo.",
"BOROMIR",
"As you wish. I care not.",
"But he too obviously does care, and when BOROMIR turns",
"away, STRIDER takes his hand off his sword.",
"The crows return to Isengard, report to SARUMAN.",
"SARUMAN",
"So, you tried to lead them over Caradhras. And",
"if that fails? Where will you go? If the",
"mountain defeats you, will you risk a more",
"dangerous road?",
"LEGOLAS runs atop the snow while the others struggle",
"through it. Stands at the edge of a cliff, listening.",
"LEGOLAS",
"There is a fell voice on the air!",
"GANDALF",
"Saruman!",
"Rocks fall from the side of the mountain, followed by",
"snow.",
"STRIDER",
"He's trying to bring down the mountain! We",
"must turn back!",
"GANDALF",
"No!",
"GANDALF tries to stop the storm, but SARUMAN is",
"reinforcing it from Isengard. Lightning strikes the",
"mountain, and LEGOLAS pulls GANDALF back from the edge just",
"before snow falls and buries them all. One by one, they dig",
"out or shake the snow off.",
"STRIDER",
"We must get off the mountain!",
"BOROMIR",
"We must take the Pass of Rohan, or take the",
"road west to my city!",
"STRIDER",
"Rohan takes us too close to Isengard!",
"GIMLI",
"If we cannot go over the mountain, I say let",
"us go under it!",
"SARUMAN",
"Moria. You fear to go into those mines. The",
"dwarves delved too greedily and too deep. You",
"know what they awoke in the darkness of Khazad-",
"Dum. Shadow and flame.",
"GANDALF",
"Let the Ringbearer decide!",
"FRODO",
"We will go through the mines!",
"GANDALF",
"So be it.",
"GIMLI",
"The walls of Moria.",
"They walk next to a dark lake. FRODO'S foot slips in the",
"water, and he scrambles back. They reach a wall framed by",
"two great trees. GANDALF scrubs away dirt to find a pattern",
"on the wall.",
"GANDALF",
"Isildin. It mirrors only starlight and",
"moonlight.",
"Moon comes out, showing the shape of a door, with writing",
"above in elvish.",
"GANDALF",
"It reads, The Gates of Durin, Lord of Moria.",
"Speak Friend and enter.",
"PIPPIN",
"What do you suppose it means?",
"GANDALF",
"Simple. If you are a friend, you speak the",
"password, and the doors open.",
"GANDALF tries a number of passwords, but none of them",
"work. ARAGORN and SAM unload the pony and let him go.",
"STRIDER",
"The mines are no place for a pony, even one so",
"brave as Bill. Go on.",
"SAM",
"Bye bye, Bill.",
"STRIDER",
"Don't worry, Sam, he knows the way home.",
"MERRY or PIPPIN is throwing rocks in the water, ARAGORN",
"stops him.",
"STRIDER",
"Don't disturb the water!",
"BOROMIR shares his suspicion.",
"GANDALF",
"This is useless!",
"Having tried any number of passwords, GANDALF sits down in",
"disgust.",
"FRODO",
"It's a riddle. What's the Elvish word for",
"friend?",
"GANDALF",
"Mellon.",
"The gates open. They go in.",
"GIMLI",
"Soon, mister elf, you will enjoy the fabled",
"hospitality of the dwarves! Roaring fires, malt",
"beer, red meat off the bone! This is the home",
"of my cousin Balin. And they call it a mine. A",
"mine!",
"BOROMIR",
"This is no mine, it's a tomb.",
"Light reveals skeletons all over",
"GIMLI",
"No!",
"LEGOLAS pulls an arrow out of one of the skeletons.",
"LEGOLAS",
"Goblins!",
"BOROMIR",
"We make for the Gap of Rohan! We should never",
"have come here! Get out! Get out!",
"FRODO is grabbed by a tentacle from the water.",
"SAM",
"Strider!",
"SAM cuts off the tentacle, then a dozen more push the",
"HOBBITS away while one grabs FRODO.",
"Tentacles dangle FRODO far above the water. ARAGORN and",
"BOROMIR chop off tentacles. When a head shows, and a giant",
"mouth, LEGOLAS puts arrows in it. ARAGORN chops off the",
"tentacle holding FRODO, BOROMIR catches him when he falls.",
"LEGOLAS puts an arrow in one of the KRAKEN'S eyes, giving",
"ARAGORN and BOROMIR time to get out of the water.",
"GANDALF",
"Into the mines!",
"They retreat to the mine. KRAKEN crumbles the gate behind",
"them.",
"GANDALF",
"Now we have but one choice. We must face the",
"long dark of Moria. Be on your guard! There are",
"older and fouler things than orcs in the deep",
"places of the world. It is a four day journey",
"to the other side. Let us hope our presence may",
"go unnoticed.",
"PIPPIN almost falls down the stairs, which are steep and",
"cluttered with debris.",
"MERRY",
"Pippin!",
"They come to the top of the stairs.",
"GANDALF",
"I have no memory of this place.",
"PIPPIN",
"Are we lost?",
"MERRY",
"No, we're not lost.",
"PIPPIN",
"I think we're lost.",
"MERRY",
"Quiet, Gandalf's thinking.",
"PIPPIN",
"Merry? I'm hungry.",
"FRODO sees something behind them.",
"FRODO",
"There's something down there.",
"GANDALF",
"It's Gollum. He's been following us for three",
"days.",
"FRODO",
"He escaped from the dungeons of Barad-dur!",
"GANDALF",
"Escaped, or was set loose. Gollum hates and",
"loves the ring, as he hates and loves himself.",
"He will never be free of his need for it.",
"FRODO",
"Pity Bilbo didn't kill him when he had the",
"chance.",
"GANDALF",
"Pity? It was pity that stayed Bilbo's hand.",
"Many who live deserve death, and some who die",
"deserve life. Can you give it to them? Do not",
"be too eager to deal out death in judgment.",
"Even the very wise cannot see all ends, but my",
"heart tells me that Gollum still has a part to",
"play, for good or ill. Before this is over, the",
"pity of Bilbo may rule the fate of many.",
"FRODO",
"I wish the ring had never come to me. I wish",
"none of this had ever happened.",
"GANDALF",
"So do all who live to see such times, but that",
"is not for them to decide. All we have to",
"decide is what to do with the time we are",
"given. There are other forces at work in the",
"world than the will of evil. Bilbo was",
"meant to find the ring, which means that",
"you also were meant to have it. And that",
"is an encouraging thought. Ah! It's this way.",
"MERRY",
"He's remembered!",
"GANDALF",
"No, but the air smells less foul down here.",
"When in doubt, Meriadoc, always follow your",
"nose.",
"GANDALF",
"Let me risk a little more light.",
"They see a huge cavern, held up with immense pillars.",
"GANDALF",
"Behold! The great realm of the dwarven city of",
"Dwarrowdelf.",
"SAM",
"Well, that's an eye-opener and no mistake!",
"GIMLI sees a door, runs through it.",
"GANDALF",
"Gimli!",
"The others follow, find GIMLI grieving over a tomb.",
"GANDALF reads the dwarven runes on the top of the tomb.",
"GANDALF",
"Here lies Balin, son of Hrundin, Lord of",
"Moria. He is dead then. It is as I feared.",
"GANDALF finds a book held by a skeleton leaning against",
"the tomb.",
"LEGOLAS",
"We must move on. We cannot linger here.",
"GANDALF",
"They have taken the bridge, and the second",
"hall. The ground shakes. We have barred the",
"gates, but cannot hold them for long. A shadow",
"moves in the dark. Drums, drums in the deep. We",
"cannot get out. We cannot get out. They are",
"coming.",
"PIPPIN knocks a skeleton into the well, which makes a",
"little more than enough noise to wake the dead.",
"GANDALF",
"Fool of a Took! Next time, throw yourself in,",
"and rid us of your stupidity!",
"There is a pause where it seems they might not have been",
"heard, then drums start pounding. FRODO'S sword is glowing",
"blue.",
"LEGOLAS",
"Orcs!",
"BOROMIR checks out the door, almost gets hit by two",
"arrows, shuts the door.",
"BOROMIR",
"They have a cave troll.",
"STRIDER",
"Stay back, close to Gandalf!",
"They bar the door with the weapons of the dead.",
"GIMLI",
"Let them come! There is one dwarf yet in Moria",
"who still draws breath!",
"ORCS break holes in the door. LEGOLAS and ARAGORN shoot",
"arrows through the holes and kill the ORCS on the other",
"side. Finally, the doors break open and ORCS flood in. All",
"the companions join in the fighting, even the HOBBITS. Then",
"the TROLL comes through the door and part of the wall. SAM",
"slips under him. Many ORCS killed. The TROLL smashes the",
"tomb GIMLI is standing on top of, but misses GIMLI, then",
"kills several of the ORCS in its attempt to get the dwarf.",
"The TROLL uses its chain like a whip, trying to hit",
"LEGOLAS, who dodges. The chain becomes momentarily caught",
"around a pillar, and LEGOLAS runs up it to stand on top of",
"the TROLL and gets a shot at its head, but jumps off when",
"the TROLL grabs for his ankles. SAM hits several ORCS over",
"the head with his frying pan.",
"SAM",
"I think I'm getting the hang of this!",
"TROLL catches sight of the three HOBBITS. They all dodge,",
"but FRODO goes one way and MERRY and PIPPIN the other. The",
"TROLL follows FRODO, who manages to stay on the opposite",
"side of the pillar from the TROLL for a while, but then he",
"is surprised, falls down, and the TROLL grabs his foot.",
"FRODO",
"Aragorn! Help!",
"FRODO cuts the TROLL'S hand with Sting, and it lets go.",
"TROLL reaches for FRODO again, but ARAGORN runs over and",
"stabs it with a spear, prompting the TROLL to smash him",
"into the wall. FRODO shakes ARAGORN, but he doesn't get up.",
"TROLL stabs at ARAGORN, but renews its interest in FRODO",
"when he moves. FRODO dodges the spear, then runs into it",
"and gets thrown against the wall. Before he can move, the",
"TROLL stabs him with the spear. FRODO falls, with the spear",
"in his side. MERRY and PIPPIN jump on the TROLL'S back and",
"stab it wildly. TROLL grabs MERRY and throws him off,",
"PIPPIN stabs it again, when it rears up, LEGOLAS kills the",
"TROLL with an arrow through the brain. PIPPIN has a hard",
"landing, still being on top of the TROLL when it falls.",
"STRIDER",
"Oh, no.",
"Thinking he's dead, STRIDER rolls FRODO over, but he sits",
"up.",
"SAM",
"He's alive!",
"FRODO",
"I'm all right, I'm not hurt.",
"STRIDER",
"You should be dead! That spear would have",
"skewered a wild boar!",
"GANDALF",
"I think there is more to this hobbit than",
"meets the eye.",
"FRODO pulls open his shirt to reveal a Mithril vest.",
"GIMLI",
"Mithril! You are full of surprises, Mr.",
"Baggins!",
"More ORCS approach.",
"GANDALF",
"To the bridge of Khazad-Dum!",
"They run through the cavern, but become surrounded by",
"ORCS. There is a roar in the distance. The ORCS all run",
"away.",
"BOROMIR",
"What is this new devilry?",
"GANDALF",
"A balrog. A demon of the ancient world. This",
"foe is beyond any of you. Run!",
"They run. BOROMIR abruptly comes to the edge of the path,",
"drops his torch and teeters on the edge of a very long",
"drop. LEGOLAS pulls him back from the edge.",
"GANDALF",
"Lead them on, Aragorn! The bridge is near. Do",
"as I say! Swords are no more use here!",
"They come to a gap in the apparently endless staircase,",
"which LEGOLAS jumps across easily. GANDALF follows after a",
"moment's hesitation. BOROMIR grabs MERRY and PIPPIN, jumps",
"across as the edge crumbles. STRIDER throws SAM across, but",
"GIMLI holds up a hand.",
"GIMLI",
"Nobody tosses a dwarf!",
"GIMLI jumps, but doesn't quite make it, and LEGOLAS grabs",
"his beard to keep him from falling.",
"GIMLI",
"Not the beard!",
"More breaks off the edge, FRODO and STRIDER scramble back.",
"The gap is now too far to jump. Part of roof breaks off,",
"breaks the section FRODO and STRIDER are on loose from the",
"rest of the stair. It starts to tilt. Trying to keep his",
"balance, STRIDER finds he can influence the direction the",
"stair falls.",
"STRIDER",
"Lean forward!",
"They do, and the section falls forward into the rest of",
"the stair, allowing FRODO and STRIDER to rejoin the party.",
"They keep running as the enormous section of stair falls",
"into the abyss. They manage to get down the stairs to level",
"ground without more trouble. As they run toward the bridge,",
"the BALROG emerges from the chasm behind them. GANDALF",
"makes sure everyone is across the bridge before he makes",
"his stand. In the center of the bridge, he turns to face",
"the demon, staff and sword in hand.",
"GANDALF",
"You cannot pass.",
"FRODO",
"Gandalf!",
"A wave of flame spreads across the BALROG.",
"GANDALF",
"I am a servant of the secret fire, wielder of",
"the flame of Anor! Dark fire shall not avail",
"you, flame of Udun!",
"BALROG draws a flaming sword and swings at GANDALF, but he",
"blocks it.",
"GANDALF",
"Go back to the shadow! You shall not",
"pass!",
"GANDALF slams his staff on the ground, and a flash of",
"white light drives the BALROG back. The demon draws a whip",
"of fire, steps onto the bridge, and the bridge gives way,",
"dropping the BALROG into the chasm. It seems they have won,",
"but as he turns away, the tail of the whip catches",
"GANDALF'S ankle and pulls him down. He gets a brief grasp",
"on the edge of the bridge.",
"GANDALF",
"Fly, you fools!",
"And GANDALF follows his enemy into the abyss.",
"FRODO",
"No!",
"FRODO tries to return to the bridge, but BOROMIR holds him",
"back.",
"BOROMIR",
"Aragorn!",
"BOROMIR carries FRODO away. ARAGORN pauses, looking back",
"until ORC arrows drive him away. The diminished group",
"escapes into the sunlight before most collapse with grief,",
"weeping for the loss of their friend. LEGOLAS seems",
"stunned. ARAGORN becomes their leader.",
"STRIDER",
"Legolas, get them up!",
"BOROMIR",
"Give them a moment, for pity's sake!",
"STRIDER",
"By nightfall these hills will be crawling with",
"orcs! We must reach the woods of Lothlorien.",
"Gimli, Legolas, get them up! On your feet, Sam.",
"Frodo?",
"FRODO has drawn away from the rest. Tears spill down his",
"face.",
"ARAGORN jogs across a very cold stream to see LOTHLORIEN",
"in the distance. After some travel, they enter LOTHLORIEN,",
"a wood of silver trees.",
"GIMLI",
"Stay close, young hobbits. They say a great",
"sorceress lives here, an elf-witch of terrible",
"power. All those who look upon her fall under",
"her spell, and are never seen again.",
"GALADRIEL",
"Frodo. Your coming is as the footsteps of",
"doom. You bring a great evil here, Ringbearer.",
"GIMLI",
"Well, this is one dwarf she won't ensnare so",
"easily! I have the eyes of a hawk, and the ears",
"of a fox!",
"Suddenly, they are all surrounded by ELVES with drawn",
"bows.",
"HALDIR",
"The dwarf breathes so loudly we could have",
"shot him in the dark.",
"STRIDER",
"Haldir of Lorien. We have come for help. We",
"need your protection.",
"GIMLI",
"Aragorn, these woods are perilous! We should",
"go back!",
"HALDIR",
"You have entered the realm of the Lady of the",
"Wood. You cannot go back. Come. She is waiting.",
"They enter the elf city in the trees, are brought before",
"Celeborn and GALADRIEL.",
"CELEBORN",
"Eight there are here, but nine there were set",
"out from Rivendell. Where is Gandalf, for I",
"much desire to speak with him.",
"GALADRIEL",
"He is fallen into shadow. The quest stands on",
"the edge of a knife, stray but a little and it",
"will fail, to the ruin of all. Yet hope remains",
"as long as the company is true. Do not let your",
"hearts be troubled. Go now, and rest, for you",
"are weary with toil and much sorrow. Tonight",
"you shall sleep in peace.",
"GALADRIEL",
"Welcome, Frodo of the Shire, one who has seen",
"the Eye.",
"There is singing in the background while they camp, more",
"comfortable on the ground than in the trees.",
"LEGOLAS",
"A lament for Gandalf.",
"What do they say about him?",
"LEGOLAS",
"I have not the heart to tell you. For me the",
"grief is still too near.",
"STRIDER",
"Take some rest, Boromir. These borders are",
"well protected.",
"BOROMIR",
"I shall find no rest here. I heard a voice",
"inside my head. She spoke of my father and the",
"fall of Gondor. She said to me, even now, there",
"is hope left, but I cannot see it. It is long",
"since we had any hope. My father is a noble",
"man, but Izual is failing, and the people lose",
"faith. My father looks to me to set it right,",
"and I would do it, I would see the glory of",
"Gondor restored. Have you seen it, Aragorn? The",
"white tower of Ecthelion glimmering like a",
"spike of pearl and silver, its banners caught",
"high in the morning breeze. Have you ever been",
"called home by the clear ringing of silver",
"trumpets?",
"STRIDER",
"I have seen the White City, long ago.",
"BOROMIR",
"One day, our paths will lead us there, and the",
"tower guard will take up the call, 'the lords",
"of Gondor have returned!'",
"ARAGORN makes no promises.",
"The company sleeps, and when GALADRIEL passes, only FRODO",
"wakes. He follows her to a basin set in stone, which she",
"fills with water from a silver urn.",
"GALADRIEL",
"Will you look into the mirror?",
"FRODO",
"What will I see?",
"GALADRIEL",
"Not even the wisest can say, for the mirror",
"shows many things. Things that are, things that",
"were, and some things that have not yet come to",
"pass.",
"FRODO looks into the mirror, and sees LEGOLAS, MERRY and",
"PIPPIN, then SAM. The Shire as it was, then the Shire",
"ravaged, overrun with ORCS, and SAM in chains. Then the EYE",
"appears, and the RING grows heavier, trying to pull itself",
"down into the mirror. FRODO snatches it away, falls",
"backward onto the ground.",
"GALADRIEL",
"I know what it is you have seen, for it is",
"also in my mind. It is what will come to pass",
"if you should fail. The Fellowship is breaking.",
"Already it has begun. He will try to take the",
"ring. You know of whom I speak. One by one, it",
"will destroy them all.",
"FRODO",
"If you ask it of me, I will give you the One",
"Ring.",
"GALADRIEL",
"You offer it to me freely. I do not deny that",
"my heart has greatly desired this.",
"A dark light comes over her as she touches the power of",
"the One RING.",
"GALADRIEL",
"Instead of a Dark Lord, you would have a",
"queen, not dark but beautiful and terrible as",
"the dawn! Tempestuous as the sea, and stronger",
"than the foundations of the earth! All shall",
"love me and despair!",
"GALADRIEL backs away from the RING, but for a moment, she",
"looks old, and it seems to bring her no joy to have done",
"the right thing.",
"GALADRIEL",
"I passed the test. I will diminish, and go",
"into the west, and remain Galadriel.",
"FRODO",
"I cannot do this alone.",
"GALADRIEL",
"You are a Ringbearer, Frodo. To bear a ring of",
"power is to be alone. This task was appointed",
"to you, and if you do not find a way, no one",
"will.",
"FRODO",
"Then, I know what I must do. It's just I am",
"afraid to do it.",
"GALADRIEL",
"Even the smallest person can change the course",
"of the future.",
"SARUMAN talking to the first URUK-HAI.",
"SARUMAN",
"Do you know how orcs first came into being?",
"They were elves once, taken by the dark powers,",
"tortured, mutilated. A ruined and terrible fall",
"of life. And now perfected, my fighting Uruk-",
"Hai. Whom do you serve?",
"Saruman.",
"Now SARUMAN addresses the army of URUK-HAI.",
"SARUMAN",
"Hunt them down. Do not stop until you have",
"found them. You do not know pain, you do not",
"know fear, you will taste man-flesh! One of the",
"halflings carries something of great value.",
"Bring them to me alive, and unspoiled! Kill the",
"others.",
"The company departs in three small boats.",
"GALADRIEL",
"Farewell, Frodo Baggins. I give you the light",
"of Earendil, our most beloved star. Numarii.",
"May it be a light for you in dark places, where",
"all other lights go out.",
"They paddle down the river a long ways.",
"URUK-HAI on the march.",
"The company comes to a bend in the river and ARAGORN taps",
"FRODO'S shoulder.",
"STRIDER",
"Frodo. The Aragornath. Long have I desired to",
"look upon the kings of old, my kin.",
"There are two enormous statues of MEN in armor flanking",
"the river, their left hands outstretched in a gesture of",
"warding. The company goes past them, into a lake, where",
"they find an old moorage and beach their boats.",
"STRIDER",
"We cross at nightfall, hide the boats and",
"continue on foot. We approach Mordor from the",
"north.",
"GIMLI",
"Oh? Just a simple matter of finding our way",
"across Emyn Muil, an impassable labyrinth of",
"razor-sharp rocks! And then it gets even",
"better! Festering, stinking marshlands as far",
"as the eye can see!",
"STRIDER",
"That is our road, sir dwarf. Perhaps you",
"should take some rest, and recover your",
"strength.",
"GIMLI",
"Recover my...!",
"LEGOLAS",
"We should leave now.",
"STRIDER",
"No. Orcs patrol the eastern shore. We must",
"wait for the cover of darkness.",
"LEGOLAS",
"It is not the eastern shore that worries me. A",
"shadow and a threat has been growing in my",
"mind. Something draws near, I can feel it.",
"GIMLI",
"Recover my strength! Pay no heed to that,",
"young hobbits.",
"MERRY returns from gathering firewood.",
"MERRY",
"Where is Frodo?",
"ARAGORN looks around and realizes BOROMIR is also missing.",
"FRODO walks in the forest, BOROMIR finds him.",
"BOROMIR",
"None of us should wander alone, you least of",
"all. So much depends on you. Frodo? I know why",
"you seek solitude. You suffer, I see it day by",
"day. Be sure you do not suffer needlessly.",
"There are other ways, Frodo, other paths we",
"might take.",
"FRODO",
"I know what you would say, and it would sound",
"like wisdom, but for the warning in my heart.",
"BOROMIR",
"Warning? Against what? They are all afraid,",
"but to let that fear drive us to destroy what",
"hope we have... Don't you see? It's madness.",
"FRODO",
"There is no other way.",
"BOROMIR",
"Why do you recoil? I am no thief.",
"FRODO",
"You are not yourself!",
"BOROMIR",
"I ask only for the strength to defend my",
"people! If you would but lend me the",
"ring.",
"FRODO",
"No!",
"BOROMIR",
"What chance do you think you have? They will",
"find you, they will take the ring, and you will",
"beg for death before the end! It is not yours",
"save by a happenstance. It could have been",
"mine. It should have been mine! Give it to me!",
"FRODO",
"No!",
"They struggle, FRODO puts on the ring and disappears.",
"BOROMIR",
"I see your mind! You would take the ring to",
"Sauron! You will betray us! You go to your",
"death, and the death of us all! Curse you!",
"Curse all you halflings!",
"BOROMIR falls, and seems to recover himself.",
"BOROMIR",
"Frodo? Frodo? What have I done? Frodo, I'm",
"sorry!",
"FRODO runs away, with the ring on. He hides atop a stone",
"platform in the woods, looks east and sees BARAD-DUR, and",
"army of ORCS, and the EYE. He falls off the platform and",
"takes off the ring. ARAGORN arrives.",
"STRIDER",
"Frodo?",
"FRODO",
"It has taken Boromir.",
"STRIDER",
"Where is the ring?",
"FRODO backs away.",
"FRODO",
"Stay away!",
"STRIDER",
"Frodo? I swore to protect you.",
"FRODO",
"Can you protect me from yourself? Would",
"you destroy it?",
"ARAGORN resists the ring, but leaves it with FRODO.",
"STRIDER",
"I would have gone with you to the end, into",
"the very fires of Mordor.",
"FRODO",
"I know. Take care of the others. Especially",
"Sam, he will not understand.",
"STRIDER",
"Go, Frodo!",
"Sting is glowing.",
"STRIDER",
"Run! Run!",
"URUK",
"Find the Halflings! Find the Halflings!",
"ARAGORN fights a lot of ORCS. When the ORCS return to",
"hunting halflings, he jumps off the platform onto them.",
"LEGOLAS and GIMLI join him. When one ORC gets too close to",
"shoot, LEGOLAS stabs him in the eye with the arrow he is",
"holding, then puts it in his bow to kill the next one, too.",
"FRODO runs away, sees MERRY and PIPPIN hiding.",
"PIPPIN",
"Here, Frodo, hide here!",
"FRODO shakes his head.",
"PIPPIN",
"What's he doing?",
"MERRY",
"He's leaving.",
"PIPPIN",
"No, Frodo!",
"PIPPIN bolts from his hiding place, only to realize that",
"he has been seen by ORCS. MERRY determines that they must",
"provide a distraction so that FRODO can get away.",
"MERRY",
"Run, Frodo. Go.",
"MERRY waves his arms at the approaching ORCS.",
"MERRY",
"Hey, you, over here, this way!",
"MERRY and PIPPIN run, leading a pack of ORCS. FRODO runs",
"the other way.",
"PIPPIN",
"It's working!",
"MERRY",
"I know it's working, run!",
"BOROMIR kills a bunch of ORCS defending MERRY and PIPPIN.",
"His horn brings friends and enemies alike. BOROMIR gets",
"shot three times before he stops killing ORCS. MERRY and",
"PIPPIN get kidnapped, and the ORCS leave BOROMIR alive",
"since he can no longer fight. The URUK-HAI is going to",
"finish him off, but ARAGORN arrives, and manages to kill",
"him after extended fighting. Returns to BOROMIR after.",
"BOROMIR",
"They took the little ones.",
"STRIDER",
"Stay still.",
"BOROMIR",
"Frodo. Where is Frodo?",
"STRIDER",
"I let Frodo go.",
"BOROMIR",
"Then you did what I could not. I tried to take",
"the ring from him.",
"STRIDER",
"The ring is beyond our reach now.",
"BOROMIR",
"Forgive me. I did not see it. I have failed",
"you all.",
"STRIDER",
"No, Boromir. You fought bravely. You have kept",
"your honor.",
"ARAGORN reaches to pull out one of the arrows, but BOROMIR",
"stops him.",
"BOROMIR",
"Leave it. It's over. The world of men will",
"fail. All will fall into darkness, and my city",
"to ruin.",
"STRIDER",
"I know not what strength lies in my blood, but",
"I swear to you I will not let the White City",
"fall, nor our people fail.",
"BOROMIR",
"Our people. Our people.",
"ARAGORN gives BOROMIR back his sword.",
"BOROMIR",
"I would have followed you, my brother, my",
"captain, my king.",
"BOROMIR dies.",
"STRIDER",
"Be at peace, son of Gondor.",
"FRODO at the boats, holding the RING in his hand.",
"SAM searching for him.",
"SAM",
"Frodo! Mr. Frodo!",
"FRODO",
"I wish the ring had never come to me. I wish",
"none of this had ever happened.",
"GANDALF",
"So do all who live to see such times, but that",
"is not for them to decide. All you have to",
"decide is what to do with the time that is",
"given you.",
"FRODO regains his resolution, tucks the RING in his pocket",
"and jumps in boat. SAM arrives on shore.",
"SAM",
"Frodo! Mr. Frodo!",
"FRODO",
"No, Sam.",
"SAM starts wading in.",
"FRODO",
"Go back, Sam. I'm going to Mordor alone!",
"SAM",
"Of course you are, and I'm coming with you!",
"SAM keeps going, well into the lake.",
"FRODO",
"You can't swim! Sam!",
"SAM gets in over his head, FRODO turns around and pulls",
"him into the boat.",
"SAM",
"I made a promise, Mr. Frodo. A promise. Don't",
"you leave him, Samwise Gamgee, and I don't mean",
"to. I don't mean to.",
"FRODO",
"Oh, Sam. Come on.",
"They hug, then start paddling across the lake.",
"BOROMIR'S body, in one of the boats, floats over the",
"waterfall. LEGOLAS pushes the last boat to the water.",
"LEGOLAS",
"Hurry! Frodo and Sam have reached the eastern",
"shore!",
"ARAGORN buckles on BOROMIR'S bracers, with the white tree",
"of Gondor. LEGOLAS realizes that ARAGORN isn't coming.",
"LEGOLAS",
"You mean not to follow them.",
"STRIDER",
"Frodo's fate no longer rests in our hands.",
"GIMLI",
"Then it was all in vain. The Fellowship has",
"failed.",
"STRIDER",
"Not as long as we remain true to each other.",
"We will not abandon Merry and Pippin to torment",
"and death. Not while we have strength left.",
"Leave all that can be spared behind, we travel",
"light. Let us hunt some orc.",
"GIMLI and LEGOLAS agree, and the three set off in pursuit.",
"FRODO and SAM reach a height from which they can see the",
"path ahead.",
"FRODO",
"Mordor. I hope the others find a safer road.",
"SAM",
"Strider will take care of them.",
"FRODO",
"I don't suppose we'll ever see them again.",
"SAM",
"We may yet, Mr. Frodo. We may.",
"FRODO",
"Sam, I'm glad you're with me.",
"THE END",
]